### ISSUE TITLE
Exception during test

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-namematching-service#2]
Just for the record, I get some exception during a test search, I'm not sure if I'm using correctly:
https://bie.ala.org.au/search?q=ruminantium
in the 
http://localhost:9179/api/search?q=ruminantium
I get:
```
ala-namematching-service-back | 172.24.0.1 - - [18/Jun/2020:15:59:10 +0000] "GET /api/search?q=ruminantium HTTP/1.1" 200 432 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/83.0.4103.61 Chrome/83.0.4103.61 Safari/537.36" 136
ala-namematching-service-back | WARN  [2020-06-18 15:59:12,710] au.org.ala.names.search.ALANameSearcher: Unable to parse ruminantium. Name of type unkown unparsable: ruminantium
ala-namematching-service-back | ! org.gbif.ecat.parser.UnparsableException: Name of type unkown unparsable: ruminantium
ala-namematching-service-back | ! at org.gbif.ecat.parser.NameParser.parse(NameParser.java:737)
ala-namematching-service-back | ! at au.org.ala.names.parser.PhraseNameParser.parse(PhraseNameParser.java:118)
ala-namematching-service-back | ! at au.org.ala.names.search.ALANameSearcher.searchForRecords(ALANameSearcher.java:1015)
ala-namematching-service-back | ! at au.org.ala.names.search.ALANameSearcher.searchForRecords(ALANameSearcher.java:963)
ala-namematching-service-back | ! at au.org.ala.names.search.ALANameSearcher.searchForRecord(ALANameSearcher.java:866)
ala-namematching-service-back | ! at au.org.ala.names.search.ALANameSearcher.searchForRecord(ALANameSearcher.java:850)
ala-namematching-service-back | ! at au.org.ala.names.search.ALANameSearcher.searchForRecord(ALANameSearcher.java:742)
ala-namematching-service-back | ! at au.org.ala.names.search.ALANameSearcher.searchForRecord(ALANameSearcher.java:753)
ala-namematching-service-back | ! at au.org.ala.names.ws.resources.NameSearchResource.search(NameSearchResource.java:201)
ala-namematching-service-back | ! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ala-namematching-service-back | ! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ala-namematching-service-back | ! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ala-namematching-service-back | ! at java.lang.reflect.Method.invoke(Method.java:498)
ala-namematching-service-back | ! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
ala-namematching-service-back | ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
ala-namematching-service-back | ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
ala-namematching-service-back | ! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
ala-namematching-service-back | ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
ala-namematching-service-back | ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
ala-namematching-service-back | ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
ala-namematching-service-back | ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
ala-namematching-service-back | ! at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
ala-namematching-service-back | ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
ala-namematching-service-back | ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
ala-namematching-service-back | ! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
ala-namematching-service-back | ! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
ala-namematching-service-back | ! at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
ala-namematching-service-back | ! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
ala-namematching-service-back | ! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
ala-namematching-service-back | ! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
ala-namematching-service-back | ! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
ala-namematching-service-back | ! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
ala-namematching-service-back | ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
ala-namematching-service-back | ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
ala-namematching-service-back | ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
ala-namematching-service-back | ! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:50)
ala-namematching-service-back | ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
ala-namematching-service-back | ! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
ala-namematching-service-back | ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
ala-namematching-service-back | ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
ala-namematching-service-back | ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
ala-namematching-service-back | ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
ala-namematching-service-back | ! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
ala-namematching-service-back | ! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
ala-namematching-service-back | ! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:249)
ala-namematching-service-back | ! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
ala-namematching-service-back | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
ala-namematching-service-back | ! at org.eclipse.jetty.server.Server.handle(Server.java:500)
ala-namematching-service-back | ! at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
ala-namematching-service-back | ! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
ala-namematching-service-back | ! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
ala-namematching-service-back | ! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
ala-namematching-service-back | ! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
ala-namematching-service-back | ! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
ala-namematching-service-back | ! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
ala-namematching-service-back | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
ala-namematching-service-back | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
ala-namematching-service-back | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
ala-namematching-service-back | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
ala-namematching-service-back | ! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
ala-namematching-service-back | ! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
```

**Comment by vjrj** [comment]
Now does not fails as before. Thanks
